M48
; DRILL file {KiCad 8.0.8} date 2025-02-17T20:57:00-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-17T20:57:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T2
X5.2717Y-1.6535
T1
G00X5.0984Y-1.6634
M15
G01X5.0984Y-1.6437
M16
G05
M30
